spring:
  application:
    name: Weather API
  datasource:
    url: jdbc:h2:mem:weather
    username: sa
    password: password44
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
